version: '3'

services:
  image3d-env:
    image: gnasello/image3d-env:2023-01-19
    build: .
    ports:
      - $JUPYTERPORT:$JUPYTERPORT
    volumes:
      - $HOME_RESEARCHER:/home/sliceruser/work
    user: root
    working_dir: /home/sliceruser
    container_name: $COMPOSE_PROJECT_NAME
    #entrypoint: bash /entrypoint.sh
    hostname: $HOST_NAME
    environment:
       - JUPYTERPORT=${JUPYTERPORT}
       - USER_RESEARCHER=${USER_RESEARCHER}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
