version: '3'

services:
  image3d:
    image: gnasello/image3d-env:2023-01-23
    build: .
    ports:
      - $JUPYTERPORT:$JUPYTERPORT
    volumes:
      - $HOME_RESEARCHER:/home/sliceruser/work
    user: root
    working_dir: /home/sliceruser/work
    environment:
       - JUPYTERPORT=${JUPYTERPORT}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
