version: '3'

services:
  image3d:
    image: Dockerfile
    build: .
    ports:
      - $JUPYTERPORT:$JUPYTERPORT
    volumes:
      - $HOME_RESEARCHER:/home/researcher
    user: root
    working_dir: /home/researcher
    container_name: $COMPOSE_PROJECT_NAME
    entrypoint: bash /entrypoint.sh
    hostname: $HOST_NAME
    environment:
       - JUPYTERPORT=${JUPYTERPORT}
       - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
       - HOST_NAME=${HOST_NAME}
       - HOME_RESEARCHER=${HOME_RESEARCHER}
